name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
